### ISSUE TITLE
Three.JS communication back to Julia?

### ISSUE THREAD

**Issue by izaid** [rohitvarkey/ThreeJS.jl#31]
Very nice package! I'm just wondering if there is a way to send information back to Julia -- e.g. the coordinates of a Three.JS pick from raycasting, or whatever.

**Comment by izaid** [comment]
@rohitvarkey Any ideas here? I'd like to make this work. I'm thinking an approach similar to https://github.com/EricForgy/JavaScriptBridge.jl could work.

If you have no preference, I'll figure something out and make a PR. I basically want the ThreeJS raycaster to callback into Julia.

**Comment by rohitvarkey** [comment]
Sure. Any approach that works is fine with me.

**Comment by izaid** [comment]
Closing this, because I got something working in the raycaster PR.
