### ISSUE TITLE
three-js as a Git subrepository?

### ISSUE THREAD

**Issue by izaid** [rohitvarkey/ThreeJS.jl#36]
So, I'm just trying to optimize my workflow for making PRs to `ThreeJS.jl`. Is there a good way to edit branches of `three-js` and `ThreeJS.jl` at the same time? If not, maybe we should add `three-js` as a Git subrepository here?

**Comment by rohitvarkey** [comment]
Setting `three-js` as a submodule would make things easier to work with. Can you come up a PR to do so?

**Comment by izaid** [comment]
Yeah, I can do it. I'm just thinking about it atm though. This may interact badly with Julia's package manager, which doesn't handle subrepositories.

**Comment by rohitvarkey** [comment]
> This may interact badly with Julia's package manager, which doesn't handle subrepositories.

In that case, sticking with the current approach would be a better option I feel.

**Comment by izaid** [comment]
Fixed this now.
